### ISSUE TITLE
Open discussions tab for contact request

### ISSUE THREAD

**Issue by KendallDoesCoding** [schmelto/schmelto#22]
Hi,

Please open discussions on this repo, or accept my friend req on discord Kendall#9903

Thanks

**Comment by KendallDoesCoding** [comment]
??

**Comment by schmelto** [comment]
@KendallDoesCoding Ive accepted your friend request on discord that's why I closed this issue here. Further I don't want to open discussion on this repo due its only my personal GitHub profile. If you want to reach out to me you could connect with me on LinkedIn or twitter. Further on my portfolio website is an email form. 
Regards

**Comment by KendallDoesCoding** [comment]
Thanks will do!
